node-jenkins-app-example:
  restart: always
  image: node-jenkins-app-example
  build: ./node-jenkins-app-example
  container_name: node-jenkins-app-example
  environment:
    - VIRTUAL_HOST=PUTSUBDOMAINHERE.harveydelaney.com
    - VIRTUAL_PORT=3000