// Auth Actions
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

// GET User List
export const GET_USER_LIST = 'GET_USER_LIST'
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS'
export const GET_USER_LIST_FAILED = 'GET_USER_LIST_FAILED'

// Create form
export const CREATE_FORM = 'CREATE_FORM'
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAILED = 'CREATE_FORM_FAILED'

export const GET_FORM = 'GET_FORM'
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const GET_FORM_FAILED = 'GET_FORM_FAILED'

export const GET_FORM_LIST = 'GET_FORM_LIST'
export const GET_FORM_LIST_SUCCESS = 'GET_FORM_LIST_SUCCESS'
export const GET_FORM_LIST_FAILED = 'GET_FORM_LIST_FAILED'
// user by id
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILED = 'GET_USER_BY_ID_FAILED'

// Update User
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

// Delete User
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'

// Update User Status
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS'
export const UPDATE_USER_STATUS_FAILED = 'UPDATE_USER_STATUS_FAILED'

// Update Question Form
export const UPDATE_QUESTION_FORM = 'UPDATE_QUESTION_FORM'
export const UPDATE_QUESTION_FORM_SUCCESS = 'UPDATE_QUESTION_FORM_SUCCESS'
export const UPDATE_QUESTION_FORM_FAILED = 'UPDATE_QUESTION_FORM_FAILED'

// Update Question Form
export const GET_FORM_BY_ID = 'GET_FORM_BY_ID'
export const GET_FORM_BY_ID_SUCCESS = 'GET_FORM_BY_ID_SUCCESS'
export const GET_FORM_BY_ID_FAILED = 'GET_FORM_BY_ID_FAILED'

// Delete Form
export const DELETE_FORM = 'DELETE_FORM'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'
export const DELETE_FORM_FAILED = 'DELETE_FORM_FAILED'
